### ISSUE TITLE
Error Websocket closed

### ISSUE THREAD

**Issue by dekkerj1** [pla1/PlayOnKodi#1]
Hi,
My configuration: Ubuntu touch 15.04 (OTA-10.1), Nexus 4 / BQ-M10 and installed Play on Kodi version 1.0.6 on both devices.
The app Play-on-kodi won't connect to Kodi. Error message: “Message Websocket closed. Will retry.”
I've tried several port numbers and "Allow programs on other systems etc." is enabled.
The app Kodimote works without problems and I can also connect from other devices (Android Yatze and Ubuntu laptop). 
Do you have any suggestions? 
Greetings
Jaap Dekker.

**Comment by pla1** [comment]
@dekkerj1 Sorry I missed this issue. Perhaps see if port 9090 is open by executing `nmap Your_Kodi_IP`. Thanks, PLA

**Comment by pla1** [comment]
Try installing latest version 1.1.2. Reopen this issue if it is still broken. Thanks, PLA
