### ISSUE TITLE
After trying to add a mac as device, play on kody shows this

### ISSUE THREAD

**Issue by XaRz** [pla1/PlayOnKodi#2]
![screenshot20160718_152631648](https://cloud.githubusercontent.com/assets/6230850/16916268/49af0fd0-4cfc-11e6-9023-698fce412b3e.png)

**Comment by XaRz** [comment]
I can't get there app working anymore.
I'm on Ubuntu Touch OTA11, in a M10 FHD tablet

**Comment by pla1** [comment]
Try installing latest version 1.1.2. Reopen this issue if still broken. Thanks, PLA
